name: CI

"on": [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0 # full history for metadata
          submodules: true

      - name: Pull LFS files
        run: |
          git lfs install
          git config -f .lfsconfig lfs.url https://git-lfs.lsst.cloud/lsst-dm/milestones
          git lfs pull
        working-directory: ./milestones

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Python install
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install -r milestones/requirements.txt

      - name: Install Graphviz
        run: |
          sudo apt-get update
          sudo apt-get -y install graphviz

      - name: Build
        run: |
          PYTHONPATH=milestones make html

      - name: Upload
        if: ${{ github.event_name == 'push' }}
        env:
          LTD_PASSWORD: ${{ secrets.LTD_PASSWORD }}
          LTD_USERNAME: ${{ secrets.LTD_USERNAME }}
        run: |
          ltd upload --gh --dir _build/html --product sitcomtn-052
